version: '3'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=tcg-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - sharedNetwork
  doanthaybinh:
    build:
      context: .
      dockerfile: .dockerfile
    ports:
      - "8080:8080"
    networks:
      - sharedNetwork
    env_file:
      - .env
    depends_on:
      - db
    
networks:
  sharedNetwork:
    driver: bridge

